spring:
    jpa:
        hibernate:
            ddl-auto: update

        show-sql: true

    datasource:
        url: jdbc:mysql://localhost/demo
        username: demo
        password: demo

logging:
    level:
        com.example.krosmunityBack : debug
    pattern:
        console: ${CONSOLE_LOG_PATTERN:%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(-){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}
